spring:
  application:
    name: tlias-web-managment
  datasource:
    url: jdbc:mysql://192.168.116.102:3306/tlias
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    #连接池类型,原本是hikari追光者
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #用于sql的名字和类名字的驼峰的映射
    map-underscore-to-camel-case: true

aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: yun-bucket-test
    region: cn-beijing
minio:
  endpoint: http://raspberrypi.tail703721.ts.net:19000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: tlias
#logging:
#  level:
#    org.springframework.jdbc.support.JdbcTransactionManager: debug
#    com.tk.tliaswebmanagment.Mapper: debug
#    com.tk.tliaswebmanagment.Service.impl.ClazzServiceImpl: debug
#    com.tk.tliaswebmanagment.Controller.ClazzController: debug
#    org.apache.ibatis: debug
