spring:
  application:
    name: tlias-web-managment
  datasource:
    url: jdbc:mysql://localhost:3306/tlias
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    #连接池类型,原本是hikari追光者
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #用于sql的名字和类名字的驼峰的映射
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: yun-bucket-test
    region: cn-beijing

